<?php
namespace WP2Aws\GameLift;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **Amazon GameLift** service.
 *
 * @method \WP2Aws\Result createAlias(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAliasAsync(array $args = [])
 * @method \WP2Aws\Result createBuild(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createBuildAsync(array $args = [])
 * @method \WP2Aws\Result createFleet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createFleetAsync(array $args = [])
 * @method \WP2Aws\Result createGameSession(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createGameSessionAsync(array $args = [])
 * @method \WP2Aws\Result createGameSessionQueue(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createGameSessionQueueAsync(array $args = [])
 * @method \WP2Aws\Result createPlayerSession(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPlayerSessionAsync(array $args = [])
 * @method \WP2Aws\Result createPlayerSessions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPlayerSessionsAsync(array $args = [])
 * @method \WP2Aws\Result deleteAlias(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteAliasAsync(array $args = [])
 * @method \WP2Aws\Result deleteBuild(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteBuildAsync(array $args = [])
 * @method \WP2Aws\Result deleteFleet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteFleetAsync(array $args = [])
 * @method \WP2Aws\Result deleteGameSessionQueue(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteGameSessionQueueAsync(array $args = [])
 * @method \WP2Aws\Result deleteScalingPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteScalingPolicyAsync(array $args = [])
 * @method \WP2Aws\Result describeAlias(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAliasAsync(array $args = [])
 * @method \WP2Aws\Result describeBuild(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeBuildAsync(array $args = [])
 * @method \WP2Aws\Result describeEC2InstanceLimits(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEC2InstanceLimitsAsync(array $args = [])
 * @method \WP2Aws\Result describeFleetAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeFleetAttributesAsync(array $args = [])
 * @method \WP2Aws\Result describeFleetCapacity(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeFleetCapacityAsync(array $args = [])
 * @method \WP2Aws\Result describeFleetEvents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeFleetEventsAsync(array $args = [])
 * @method \WP2Aws\Result describeFleetPortSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeFleetPortSettingsAsync(array $args = [])
 * @method \WP2Aws\Result describeFleetUtilization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeFleetUtilizationAsync(array $args = [])
 * @method \WP2Aws\Result describeGameSessionDetails(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeGameSessionDetailsAsync(array $args = [])
 * @method \WP2Aws\Result describeGameSessionPlacement(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeGameSessionPlacementAsync(array $args = [])
 * @method \WP2Aws\Result describeGameSessionQueues(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeGameSessionQueuesAsync(array $args = [])
 * @method \WP2Aws\Result describeGameSessions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeGameSessionsAsync(array $args = [])
 * @method \WP2Aws\Result describeInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeInstancesAsync(array $args = [])
 * @method \WP2Aws\Result describePlayerSessions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describePlayerSessionsAsync(array $args = [])
 * @method \WP2Aws\Result describeRuntimeConfiguration(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeRuntimeConfigurationAsync(array $args = [])
 * @method \WP2Aws\Result describeScalingPolicies(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeScalingPoliciesAsync(array $args = [])
 * @method \WP2Aws\Result getGameSessionLogUrl(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getGameSessionLogUrlAsync(array $args = [])
 * @method \WP2Aws\Result getInstanceAccess(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getInstanceAccessAsync(array $args = [])
 * @method \WP2Aws\Result listAliases(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAliasesAsync(array $args = [])
 * @method \WP2Aws\Result listBuilds(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listBuildsAsync(array $args = [])
 * @method \WP2Aws\Result listFleets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listFleetsAsync(array $args = [])
 * @method \WP2Aws\Result putScalingPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putScalingPolicyAsync(array $args = [])
 * @method \WP2Aws\Result requestUploadCredentials(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise requestUploadCredentialsAsync(array $args = [])
 * @method \WP2Aws\Result resolveAlias(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise resolveAliasAsync(array $args = [])
 * @method \WP2Aws\Result searchGameSessions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise searchGameSessionsAsync(array $args = [])
 * @method \WP2Aws\Result startGameSessionPlacement(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startGameSessionPlacementAsync(array $args = [])
 * @method \WP2Aws\Result stopGameSessionPlacement(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise stopGameSessionPlacementAsync(array $args = [])
 * @method \WP2Aws\Result updateAlias(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateAliasAsync(array $args = [])
 * @method \WP2Aws\Result updateBuild(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateBuildAsync(array $args = [])
 * @method \WP2Aws\Result updateFleetAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateFleetAttributesAsync(array $args = [])
 * @method \WP2Aws\Result updateFleetCapacity(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateFleetCapacityAsync(array $args = [])
 * @method \WP2Aws\Result updateFleetPortSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateFleetPortSettingsAsync(array $args = [])
 * @method \WP2Aws\Result updateGameSession(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateGameSessionAsync(array $args = [])
 * @method \WP2Aws\Result updateGameSessionQueue(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateGameSessionQueueAsync(array $args = [])
 * @method \WP2Aws\Result updateRuntimeConfiguration(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateRuntimeConfigurationAsync(array $args = [])
 */
class GameLiftClient extends WP2AwsClient {}
