<?php
namespace WP2Aws\ElasticLoadBalancingV2;

use WP2Aws\WP2AwsClient;
use WP2Aws\Command;
use WP2Aws\CommandInterface;
use Psr\Http\Message\RequestInterface;

/**
 * This client is used to interact with the **Elastic Load Balancing** service.
 * @method \WP2Aws\Result addTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addTagsAsync(array $args = [])
 * @method \WP2Aws\Result createListener(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createListenerAsync(array $args = [])
 * @method \WP2Aws\Result createLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result createRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createRuleAsync(array $args = [])
 * @method \WP2Aws\Result createTargetGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createTargetGroupAsync(array $args = [])
 * @method \WP2Aws\Result deleteListener(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteListenerAsync(array $args = [])
 * @method \WP2Aws\Result deleteLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result deleteRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteRuleAsync(array $args = [])
 * @method \WP2Aws\Result deleteTargetGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteTargetGroupAsync(array $args = [])
 * @method \WP2Aws\Result deregisterTargets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deregisterTargetsAsync(array $args = [])
 * @method \WP2Aws\Result describeAccountLimits(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAccountLimitsAsync(array $args = [])
 * @method \WP2Aws\Result describeListeners(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeListenersAsync(array $args = [])
 * @method \WP2Aws\Result describeLoadBalancerAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoadBalancerAttributesAsync(array $args = [])
 * @method \WP2Aws\Result describeLoadBalancers(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoadBalancersAsync(array $args = [])
 * @method \WP2Aws\Result describeRules(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeRulesAsync(array $args = [])
 * @method \WP2Aws\Result describeSSLPolicies(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeSSLPoliciesAsync(array $args = [])
 * @method \WP2Aws\Result describeTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \WP2Aws\Result describeTargetGroupAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTargetGroupAttributesAsync(array $args = [])
 * @method \WP2Aws\Result describeTargetGroups(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTargetGroupsAsync(array $args = [])
 * @method \WP2Aws\Result describeTargetHealth(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTargetHealthAsync(array $args = [])
 * @method \WP2Aws\Result modifyListener(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyListenerAsync(array $args = [])
 * @method \WP2Aws\Result modifyLoadBalancerAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyLoadBalancerAttributesAsync(array $args = [])
 * @method \WP2Aws\Result modifyRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyRuleAsync(array $args = [])
 * @method \WP2Aws\Result modifyTargetGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyTargetGroupAsync(array $args = [])
 * @method \WP2Aws\Result modifyTargetGroupAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyTargetGroupAttributesAsync(array $args = [])
 * @method \WP2Aws\Result registerTargets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerTargetsAsync(array $args = [])
 * @method \WP2Aws\Result removeTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeTagsAsync(array $args = [])
 * @method \WP2Aws\Result setIpAddressType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setIpAddressTypeAsync(array $args = [])
 * @method \WP2Aws\Result setRulePriorities(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setRulePrioritiesAsync(array $args = [])
 * @method \WP2Aws\Result setSecurityGroups(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setSecurityGroupsAsync(array $args = [])
 * @method \WP2Aws\Result setSubnets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setSubnetsAsync(array $args = [])
 */
class ElasticLoadBalancingV2Client extends WP2AwsClient {}
