<?php
namespace WP2Aws\Pinpoint;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **Amazon Pinpoint** service.
 * @method \WP2Aws\Result createCampaign(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createCampaignAsync(array $args = [])
 * @method \WP2Aws\Result createImportJob(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createImportJobAsync(array $args = [])
 * @method \WP2Aws\Result createSegment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createSegmentAsync(array $args = [])
 * @method \WP2Aws\Result deleteApnsChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteApnsChannelAsync(array $args = [])
 * @method \WP2Aws\Result deleteApnsSandboxChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteApnsSandboxChannelAsync(array $args = [])
 * @method \WP2Aws\Result deleteCampaign(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteCampaignAsync(array $args = [])
 * @method \WP2Aws\Result deleteEmailChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteEmailChannelAsync(array $args = [])
 * @method \WP2Aws\Result deleteEventStream(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteEventStreamAsync(array $args = [])
 * @method \WP2Aws\Result deleteGcmChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteGcmChannelAsync(array $args = [])
 * @method \WP2Aws\Result deleteSegment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteSegmentAsync(array $args = [])
 * @method \WP2Aws\Result deleteSmsChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteSmsChannelAsync(array $args = [])
 * @method \WP2Aws\Result getApnsChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getApnsChannelAsync(array $args = [])
 * @method \WP2Aws\Result getApnsSandboxChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getApnsSandboxChannelAsync(array $args = [])
 * @method \WP2Aws\Result getApplicationSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getApplicationSettingsAsync(array $args = [])
 * @method \WP2Aws\Result getCampaign(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getCampaignAsync(array $args = [])
 * @method \WP2Aws\Result getCampaignActivities(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getCampaignActivitiesAsync(array $args = [])
 * @method \WP2Aws\Result getCampaignVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getCampaignVersionAsync(array $args = [])
 * @method \WP2Aws\Result getCampaignVersions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getCampaignVersionsAsync(array $args = [])
 * @method \WP2Aws\Result getCampaigns(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getCampaignsAsync(array $args = [])
 * @method \WP2Aws\Result getEmailChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getEmailChannelAsync(array $args = [])
 * @method \WP2Aws\Result getEndpoint(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getEndpointAsync(array $args = [])
 * @method \WP2Aws\Result getEventStream(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getEventStreamAsync(array $args = [])
 * @method \WP2Aws\Result getGcmChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getGcmChannelAsync(array $args = [])
 * @method \WP2Aws\Result getImportJob(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getImportJobAsync(array $args = [])
 * @method \WP2Aws\Result getImportJobs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getImportJobsAsync(array $args = [])
 * @method \WP2Aws\Result getSegment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSegmentAsync(array $args = [])
 * @method \WP2Aws\Result getSegmentImportJobs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSegmentImportJobsAsync(array $args = [])
 * @method \WP2Aws\Result getSegmentVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSegmentVersionAsync(array $args = [])
 * @method \WP2Aws\Result getSegmentVersions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSegmentVersionsAsync(array $args = [])
 * @method \WP2Aws\Result getSegments(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSegmentsAsync(array $args = [])
 * @method \WP2Aws\Result getSmsChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSmsChannelAsync(array $args = [])
 * @method \WP2Aws\Result putEventStream(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putEventStreamAsync(array $args = [])
 * @method \WP2Aws\Result sendMessages(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise sendMessagesAsync(array $args = [])
 * @method \WP2Aws\Result updateApnsChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApnsChannelAsync(array $args = [])
 * @method \WP2Aws\Result updateApnsSandboxChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApnsSandboxChannelAsync(array $args = [])
 * @method \WP2Aws\Result updateApplicationSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApplicationSettingsAsync(array $args = [])
 * @method \WP2Aws\Result updateCampaign(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateCampaignAsync(array $args = [])
 * @method \WP2Aws\Result updateEmailChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateEmailChannelAsync(array $args = [])
 * @method \WP2Aws\Result updateEndpoint(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateEndpointAsync(array $args = [])
 * @method \WP2Aws\Result updateEndpointsBatch(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateEndpointsBatchAsync(array $args = [])
 * @method \WP2Aws\Result updateGcmChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateGcmChannelAsync(array $args = [])
 * @method \WP2Aws\Result updateSegment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateSegmentAsync(array $args = [])
 * @method \WP2Aws\Result updateSmsChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateSmsChannelAsync(array $args = [])
 */
class PinpointClient extends WP2AwsClient {}
