<?php

/* constants */

// If this file is called directly, abort.
if (!defined('WPINC')) {
    die;
}

define('STACKMOVER_PLUGIN_BASEDIR', dirname(__FILE__));
define('STACKMOVER_PLUGIN_BASENAME', basename(dirname(__FILE__)) . '/' . basename(__FILE__));

define('STACKMOVER_PLUGIN_URL', plugins_url('', STACKMOVER_PLUGIN_BASENAME));

define('STACKMOVER_PLUGIN_VIEWSDIR', dirname(__FILE__) . DIRECTORY_SEPARATOR . 'views');

define('STACKMOVER_PLUGIN_IMAGELS0_URL', STACKMOVER_PLUGIN_URL . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'ls0.png');
define('STACKMOVER_PLUGIN_IMAGELS1_URL', STACKMOVER_PLUGIN_URL . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'ls1.png');
define('STACKMOVER_PLUGIN_IMAGELS2_URL', STACKMOVER_PLUGIN_URL . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'ls2.png');
define('STACKMOVER_PLUGIN_IMAGELS3_URL', STACKMOVER_PLUGIN_URL . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'ls3.png');
define('STACKMOVER_PLUGIN_IMAGELS4_URL', STACKMOVER_PLUGIN_URL . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'ls4.png');

define('STACKMOVER_PLUGIN_AWS_LIB', STACKMOVER_PLUGIN_BASEDIR . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'aws-3.31.3');

define('STACKMOVER_PLUGIN_LIB', STACKMOVER_PLUGIN_BASEDIR . DIRECTORY_SEPARATOR . 'lib');

define('STACKMOVER_PLUGIN_AWS_LIB_LOADER', STACKMOVER_PLUGIN_AWS_LIB . DIRECTORY_SEPARATOR . 'aws-autoloader.php');

define('STACKMOVER_SUCCESS', 1);
define('STACKMOVER_FAILURE', 0);
define('STACKMOVER_INTERRUPTED', 2);

if (!defined('STACKMOVER_LOCAL_BACKUP_DIR')) define('STACKMOVER_LOCAL_BACKUP_DIR', WP_CONTENT_DIR . '/uploads/stackmover/backup/');

// STACKMOVER_LOGFILE
if (!defined('STACKMOVER_LOGFILE')) define('STACKMOVER_LOGFILE', STACKMOVER_LOCAL_BACKUP_DIR . '/stackmover-debug.log');

if (!defined('STACKMOVER_LOCALTMPDIR')) define('STACKMOVER_LOCALTMPDIR', STACKMOVER_LOCAL_BACKUP_DIR . '/temp/');

if (!defined('STACKMOVER_LIGHTSAIL_WAITSECONDS')) define('STACKMOVER_LIGHTSAIL_WAITSECONDS', 600);

if (!defined('STACKMOVER_MAX_MULTIPART_TIMEOUT')) define('STACKMOVER_MAX_MULTIPART_TIMEOUT', 3600);


define('STACKMOVER_VERSION', 'STACKMOVER-LITE');
#define('STACKMOVER_VERSION', 'STACKMOVER-PRO');


// Misc options
//define('STACKMOVER_MYSQLDUMP_PATH', 'INSERT-MYSQLDUMP-PATH-TO-OVERWRITE-DEFAULT');


?>
