<?php
namespace WP2Aws\Inspector;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **Amazon Inspector** service.
 *
 * @method \WP2Aws\Result addAttributesToFindings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addAttributesToFindingsAsync(array $args = [])
 * @method \WP2Aws\Result createAssessmentTarget(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAssessmentTargetAsync(array $args = [])
 * @method \WP2Aws\Result createAssessmentTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAssessmentTemplateAsync(array $args = [])
 * @method \WP2Aws\Result createResourceGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createResourceGroupAsync(array $args = [])
 * @method \WP2Aws\Result deleteAssessmentRun(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteAssessmentRunAsync(array $args = [])
 * @method \WP2Aws\Result deleteAssessmentTarget(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteAssessmentTargetAsync(array $args = [])
 * @method \WP2Aws\Result deleteAssessmentTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteAssessmentTemplateAsync(array $args = [])
 * @method \WP2Aws\Result describeAssessmentRuns(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAssessmentRunsAsync(array $args = [])
 * @method \WP2Aws\Result describeAssessmentTargets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAssessmentTargetsAsync(array $args = [])
 * @method \WP2Aws\Result describeAssessmentTemplates(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAssessmentTemplatesAsync(array $args = [])
 * @method \WP2Aws\Result describeCrossAccountAccessRole(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeCrossAccountAccessRoleAsync(array $args = [])
 * @method \WP2Aws\Result describeFindings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeFindingsAsync(array $args = [])
 * @method \WP2Aws\Result describeResourceGroups(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeResourceGroupsAsync(array $args = [])
 * @method \WP2Aws\Result describeRulesPackages(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeRulesPackagesAsync(array $args = [])
 * @method \WP2Aws\Result getAssessmentReport(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getAssessmentReportAsync(array $args = [])
 * @method \WP2Aws\Result getTelemetryMetadata(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getTelemetryMetadataAsync(array $args = [])
 * @method \WP2Aws\Result listAssessmentRunAgents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAssessmentRunAgentsAsync(array $args = [])
 * @method \WP2Aws\Result listAssessmentRuns(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAssessmentRunsAsync(array $args = [])
 * @method \WP2Aws\Result listAssessmentTargets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAssessmentTargetsAsync(array $args = [])
 * @method \WP2Aws\Result listAssessmentTemplates(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAssessmentTemplatesAsync(array $args = [])
 * @method \WP2Aws\Result listEventSubscriptions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listEventSubscriptionsAsync(array $args = [])
 * @method \WP2Aws\Result listFindings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listFindingsAsync(array $args = [])
 * @method \WP2Aws\Result listRulesPackages(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listRulesPackagesAsync(array $args = [])
 * @method \WP2Aws\Result listTagsForResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \WP2Aws\Result previewAgents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise previewAgentsAsync(array $args = [])
 * @method \WP2Aws\Result registerCrossAccountAccessRole(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerCrossAccountAccessRoleAsync(array $args = [])
 * @method \WP2Aws\Result removeAttributesFromFindings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeAttributesFromFindingsAsync(array $args = [])
 * @method \WP2Aws\Result setTagsForResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setTagsForResourceAsync(array $args = [])
 * @method \WP2Aws\Result startAssessmentRun(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startAssessmentRunAsync(array $args = [])
 * @method \WP2Aws\Result stopAssessmentRun(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise stopAssessmentRunAsync(array $args = [])
 * @method \WP2Aws\Result subscribeToEvent(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise subscribeToEventAsync(array $args = [])
 * @method \WP2Aws\Result unsubscribeFromEvent(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise unsubscribeFromEventAsync(array $args = [])
 * @method \WP2Aws\Result updateAssessmentTarget(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateAssessmentTargetAsync(array $args = [])
 */
class InspectorClient extends WP2AwsClient {}
