<?php
namespace WP2Aws\CodePipeline;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **Amazon CodePipeline** service.
 *
 * @method \WP2Aws\Result acknowledgeJob(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise acknowledgeJobAsync(array $args = [])
 * @method \WP2Aws\Result acknowledgeThirdPartyJob(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise acknowledgeThirdPartyJobAsync(array $args = [])
 * @method \WP2Aws\Result createCustomActionType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createCustomActionTypeAsync(array $args = [])
 * @method \WP2Aws\Result createPipeline(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPipelineAsync(array $args = [])
 * @method \WP2Aws\Result deleteCustomActionType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteCustomActionTypeAsync(array $args = [])
 * @method \WP2Aws\Result deletePipeline(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deletePipelineAsync(array $args = [])
 * @method \WP2Aws\Result disableStageTransition(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disableStageTransitionAsync(array $args = [])
 * @method \WP2Aws\Result enableStageTransition(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise enableStageTransitionAsync(array $args = [])
 * @method \WP2Aws\Result getJobDetails(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getJobDetailsAsync(array $args = [])
 * @method \WP2Aws\Result getPipeline(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getPipelineAsync(array $args = [])
 * @method \WP2Aws\Result getPipelineExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getPipelineExecutionAsync(array $args = [])
 * @method \WP2Aws\Result getPipelineState(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getPipelineStateAsync(array $args = [])
 * @method \WP2Aws\Result getThirdPartyJobDetails(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getThirdPartyJobDetailsAsync(array $args = [])
 * @method \WP2Aws\Result listActionTypes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listActionTypesAsync(array $args = [])
 * @method \WP2Aws\Result listPipelineExecutions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listPipelineExecutionsAsync(array $args = [])
 * @method \WP2Aws\Result listPipelines(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listPipelinesAsync(array $args = [])
 * @method \WP2Aws\Result pollForJobs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise pollForJobsAsync(array $args = [])
 * @method \WP2Aws\Result pollForThirdPartyJobs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise pollForThirdPartyJobsAsync(array $args = [])
 * @method \WP2Aws\Result putActionRevision(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putActionRevisionAsync(array $args = [])
 * @method \WP2Aws\Result putApprovalResult(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putApprovalResultAsync(array $args = [])
 * @method \WP2Aws\Result putJobFailureResult(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putJobFailureResultAsync(array $args = [])
 * @method \WP2Aws\Result putJobSuccessResult(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putJobSuccessResultAsync(array $args = [])
 * @method \WP2Aws\Result putThirdPartyJobFailureResult(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putThirdPartyJobFailureResultAsync(array $args = [])
 * @method \WP2Aws\Result putThirdPartyJobSuccessResult(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putThirdPartyJobSuccessResultAsync(array $args = [])
 * @method \WP2Aws\Result retryStageExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise retryStageExecutionAsync(array $args = [])
 * @method \WP2Aws\Result startPipelineExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startPipelineExecutionAsync(array $args = [])
 * @method \WP2Aws\Result updatePipeline(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updatePipelineAsync(array $args = [])
 */
class CodePipelineClient extends WP2AwsClient {}