<?php
namespace WP2Aws\Organizations;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **AWS Organizations** service.
 * @method \WP2Aws\Result acceptHandshake(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise acceptHandshakeAsync(array $args = [])
 * @method \WP2Aws\Result attachPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise attachPolicyAsync(array $args = [])
 * @method \WP2Aws\Result cancelHandshake(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise cancelHandshakeAsync(array $args = [])
 * @method \WP2Aws\Result createAccount(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAccountAsync(array $args = [])
 * @method \WP2Aws\Result createOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result createOrganizationalUnit(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createOrganizationalUnitAsync(array $args = [])
 * @method \WP2Aws\Result createPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPolicyAsync(array $args = [])
 * @method \WP2Aws\Result declineHandshake(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise declineHandshakeAsync(array $args = [])
 * @method \WP2Aws\Result deleteOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result deleteOrganizationalUnit(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteOrganizationalUnitAsync(array $args = [])
 * @method \WP2Aws\Result deletePolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deletePolicyAsync(array $args = [])
 * @method \WP2Aws\Result describeAccount(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAccountAsync(array $args = [])
 * @method \WP2Aws\Result describeCreateAccountStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeCreateAccountStatusAsync(array $args = [])
 * @method \WP2Aws\Result describeHandshake(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeHandshakeAsync(array $args = [])
 * @method \WP2Aws\Result describeOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result describeOrganizationalUnit(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeOrganizationalUnitAsync(array $args = [])
 * @method \WP2Aws\Result describePolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describePolicyAsync(array $args = [])
 * @method \WP2Aws\Result detachPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise detachPolicyAsync(array $args = [])
 * @method \WP2Aws\Result disablePolicyType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disablePolicyTypeAsync(array $args = [])
 * @method \WP2Aws\Result enableAllFeatures(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise enableAllFeaturesAsync(array $args = [])
 * @method \WP2Aws\Result enablePolicyType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise enablePolicyTypeAsync(array $args = [])
 * @method \WP2Aws\Result inviteAccountToOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise inviteAccountToOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result leaveOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise leaveOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result listAccounts(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAccountsAsync(array $args = [])
 * @method \WP2Aws\Result listAccountsForParent(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAccountsForParentAsync(array $args = [])
 * @method \WP2Aws\Result listChildren(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listChildrenAsync(array $args = [])
 * @method \WP2Aws\Result listCreateAccountStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listCreateAccountStatusAsync(array $args = [])
 * @method \WP2Aws\Result listHandshakesForAccount(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listHandshakesForAccountAsync(array $args = [])
 * @method \WP2Aws\Result listHandshakesForOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listHandshakesForOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result listOrganizationalUnitsForParent(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listOrganizationalUnitsForParentAsync(array $args = [])
 * @method \WP2Aws\Result listParents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listParentsAsync(array $args = [])
 * @method \WP2Aws\Result listPolicies(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listPoliciesAsync(array $args = [])
 * @method \WP2Aws\Result listPoliciesForTarget(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listPoliciesForTargetAsync(array $args = [])
 * @method \WP2Aws\Result listRoots(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listRootsAsync(array $args = [])
 * @method \WP2Aws\Result listTargetsForPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTargetsForPolicyAsync(array $args = [])
 * @method \WP2Aws\Result moveAccount(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise moveAccountAsync(array $args = [])
 * @method \WP2Aws\Result removeAccountFromOrganization(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeAccountFromOrganizationAsync(array $args = [])
 * @method \WP2Aws\Result updateOrganizationalUnit(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateOrganizationalUnitAsync(array $args = [])
 * @method \WP2Aws\Result updatePolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updatePolicyAsync(array $args = [])
 */
class OrganizationsClient extends WP2AwsClient {}
