<?php
namespace WP2Aws\DirectoryService;

use WP2Aws\WP2AwsClient;

/**
 * AWS Directory Service client
 *
 * @method \WP2Aws\Result addIpRoutes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addIpRoutesAsync(array $args = [])
 * @method \WP2Aws\Result addTagsToResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addTagsToResourceAsync(array $args = [])
 * @method \WP2Aws\Result cancelSchemaExtension(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise cancelSchemaExtensionAsync(array $args = [])
 * @method \WP2Aws\Result connectDirectory(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise connectDirectoryAsync(array $args = [])
 * @method \WP2Aws\Result createAlias(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAliasAsync(array $args = [])
 * @method \WP2Aws\Result createComputer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createComputerAsync(array $args = [])
 * @method \WP2Aws\Result createConditionalForwarder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createConditionalForwarderAsync(array $args = [])
 * @method \WP2Aws\Result createDirectory(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createDirectoryAsync(array $args = [])
 * @method \WP2Aws\Result createMicrosoftAD(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createMicrosoftADAsync(array $args = [])
 * @method \WP2Aws\Result createSnapshot(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createSnapshotAsync(array $args = [])
 * @method \WP2Aws\Result createTrust(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createTrustAsync(array $args = [])
 * @method \WP2Aws\Result deleteConditionalForwarder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteConditionalForwarderAsync(array $args = [])
 * @method \WP2Aws\Result deleteDirectory(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteDirectoryAsync(array $args = [])
 * @method \WP2Aws\Result deleteSnapshot(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteSnapshotAsync(array $args = [])
 * @method \WP2Aws\Result deleteTrust(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteTrustAsync(array $args = [])
 * @method \WP2Aws\Result deregisterEventTopic(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deregisterEventTopicAsync(array $args = [])
 * @method \WP2Aws\Result describeConditionalForwarders(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConditionalForwardersAsync(array $args = [])
 * @method \WP2Aws\Result describeDirectories(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeDirectoriesAsync(array $args = [])
 * @method \WP2Aws\Result describeDomainControllers(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeDomainControllersAsync(array $args = [])
 * @method \WP2Aws\Result describeEventTopics(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEventTopicsAsync(array $args = [])
 * @method \WP2Aws\Result describeSnapshots(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeSnapshotsAsync(array $args = [])
 * @method \WP2Aws\Result describeTrusts(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTrustsAsync(array $args = [])
 * @method \WP2Aws\Result disableRadius(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disableRadiusAsync(array $args = [])
 * @method \WP2Aws\Result disableSso(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disableSsoAsync(array $args = [])
 * @method \WP2Aws\Result enableRadius(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise enableRadiusAsync(array $args = [])
 * @method \WP2Aws\Result enableSso(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise enableSsoAsync(array $args = [])
 * @method \WP2Aws\Result getDirectoryLimits(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getDirectoryLimitsAsync(array $args = [])
 * @method \WP2Aws\Result getSnapshotLimits(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSnapshotLimitsAsync(array $args = [])
 * @method \WP2Aws\Result listIpRoutes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listIpRoutesAsync(array $args = [])
 * @method \WP2Aws\Result listSchemaExtensions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listSchemaExtensionsAsync(array $args = [])
 * @method \WP2Aws\Result listTagsForResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \WP2Aws\Result registerEventTopic(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerEventTopicAsync(array $args = [])
 * @method \WP2Aws\Result removeIpRoutes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeIpRoutesAsync(array $args = [])
 * @method \WP2Aws\Result removeTagsFromResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeTagsFromResourceAsync(array $args = [])
 * @method \WP2Aws\Result restoreFromSnapshot(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise restoreFromSnapshotAsync(array $args = [])
 * @method \WP2Aws\Result startSchemaExtension(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startSchemaExtensionAsync(array $args = [])
 * @method \WP2Aws\Result updateConditionalForwarder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateConditionalForwarderAsync(array $args = [])
 * @method \WP2Aws\Result updateNumberOfDomainControllers(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateNumberOfDomainControllersAsync(array $args = [])
 * @method \WP2Aws\Result updateRadius(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateRadiusAsync(array $args = [])
 * @method \WP2Aws\Result verifyTrust(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise verifyTrustAsync(array $args = [])
 */
class DirectoryServiceClient extends WP2AwsClient {}
