<?php
namespace WP2Aws\MTurk;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **Amazon Mechanical Turk Requester Service** service.
 * @method \WP2Aws\Result acceptQualificationRequest(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise acceptQualificationRequestAsync(array $args = [])
 * @method \WP2Aws\Result approveAssignment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise approveAssignmentAsync(array $args = [])
 * @method \WP2Aws\Result associateQualificationWithWorker(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise associateQualificationWithWorkerAsync(array $args = [])
 * @method \WP2Aws\Result createAdditionalAssignmentsForHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAdditionalAssignmentsForHITAsync(array $args = [])
 * @method \WP2Aws\Result createHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createHITAsync(array $args = [])
 * @method \WP2Aws\Result createHITType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createHITTypeAsync(array $args = [])
 * @method \WP2Aws\Result createHITWithHITType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createHITWithHITTypeAsync(array $args = [])
 * @method \WP2Aws\Result createQualificationType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createQualificationTypeAsync(array $args = [])
 * @method \WP2Aws\Result createWorkerBlock(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createWorkerBlockAsync(array $args = [])
 * @method \WP2Aws\Result deleteHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteHITAsync(array $args = [])
 * @method \WP2Aws\Result deleteQualificationType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteQualificationTypeAsync(array $args = [])
 * @method \WP2Aws\Result deleteWorkerBlock(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteWorkerBlockAsync(array $args = [])
 * @method \WP2Aws\Result disassociateQualificationFromWorker(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disassociateQualificationFromWorkerAsync(array $args = [])
 * @method \WP2Aws\Result getAccountBalance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getAccountBalanceAsync(array $args = [])
 * @method \WP2Aws\Result getAssignment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getAssignmentAsync(array $args = [])
 * @method \WP2Aws\Result getFileUploadURL(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getFileUploadURLAsync(array $args = [])
 * @method \WP2Aws\Result getHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getHITAsync(array $args = [])
 * @method \WP2Aws\Result getQualificationScore(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getQualificationScoreAsync(array $args = [])
 * @method \WP2Aws\Result getQualificationType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getQualificationTypeAsync(array $args = [])
 * @method \WP2Aws\Result listAssignmentsForHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAssignmentsForHITAsync(array $args = [])
 * @method \WP2Aws\Result listBonusPayments(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listBonusPaymentsAsync(array $args = [])
 * @method \WP2Aws\Result listHITs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listHITsAsync(array $args = [])
 * @method \WP2Aws\Result listHITsForQualificationType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listHITsForQualificationTypeAsync(array $args = [])
 * @method \WP2Aws\Result listQualificationRequests(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listQualificationRequestsAsync(array $args = [])
 * @method \WP2Aws\Result listQualificationTypes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listQualificationTypesAsync(array $args = [])
 * @method \WP2Aws\Result listReviewPolicyResultsForHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listReviewPolicyResultsForHITAsync(array $args = [])
 * @method \WP2Aws\Result listReviewableHITs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listReviewableHITsAsync(array $args = [])
 * @method \WP2Aws\Result listWorkerBlocks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listWorkerBlocksAsync(array $args = [])
 * @method \WP2Aws\Result listWorkersWithQualificationType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listWorkersWithQualificationTypeAsync(array $args = [])
 * @method \WP2Aws\Result notifyWorkers(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise notifyWorkersAsync(array $args = [])
 * @method \WP2Aws\Result rejectAssignment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise rejectAssignmentAsync(array $args = [])
 * @method \WP2Aws\Result rejectQualificationRequest(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise rejectQualificationRequestAsync(array $args = [])
 * @method \WP2Aws\Result sendBonus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise sendBonusAsync(array $args = [])
 * @method \WP2Aws\Result sendTestEventNotification(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise sendTestEventNotificationAsync(array $args = [])
 * @method \WP2Aws\Result updateExpirationForHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateExpirationForHITAsync(array $args = [])
 * @method \WP2Aws\Result updateHITReviewStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateHITReviewStatusAsync(array $args = [])
 * @method \WP2Aws\Result updateHITTypeOfHIT(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateHITTypeOfHITAsync(array $args = [])
 * @method \WP2Aws\Result updateNotificationSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateNotificationSettingsAsync(array $args = [])
 * @method \WP2Aws\Result updateQualificationType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateQualificationTypeAsync(array $args = [])
 */
class MTurkClient extends WP2AwsClient {}
