<?php
namespace WP2Aws\ConfigService;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with AWS Config.
 *
 * @method \WP2Aws\Result deleteConfigRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteConfigRuleAsync(array $args = [])
 * @method \WP2Aws\Result deleteConfigurationRecorder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteConfigurationRecorderAsync(array $args = [])
 * @method \WP2Aws\Result deleteDeliveryChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteDeliveryChannelAsync(array $args = [])
 * @method \WP2Aws\Result deleteEvaluationResults(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteEvaluationResultsAsync(array $args = [])
 * @method \WP2Aws\Result deliverConfigSnapshot(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deliverConfigSnapshotAsync(array $args = [])
 * @method \WP2Aws\Result describeComplianceByConfigRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeComplianceByConfigRuleAsync(array $args = [])
 * @method \WP2Aws\Result describeComplianceByResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeComplianceByResourceAsync(array $args = [])
 * @method \WP2Aws\Result describeConfigRuleEvaluationStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConfigRuleEvaluationStatusAsync(array $args = [])
 * @method \WP2Aws\Result describeConfigRules(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConfigRulesAsync(array $args = [])
 * @method \WP2Aws\Result describeConfigurationRecorderStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConfigurationRecorderStatusAsync(array $args = [])
 * @method \WP2Aws\Result describeConfigurationRecorders(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConfigurationRecordersAsync(array $args = [])
 * @method \WP2Aws\Result describeDeliveryChannelStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeDeliveryChannelStatusAsync(array $args = [])
 * @method \WP2Aws\Result describeDeliveryChannels(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeDeliveryChannelsAsync(array $args = [])
 * @method \WP2Aws\Result getComplianceDetailsByConfigRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getComplianceDetailsByConfigRuleAsync(array $args = [])
 * @method \WP2Aws\Result getComplianceDetailsByResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getComplianceDetailsByResourceAsync(array $args = [])
 * @method \WP2Aws\Result getComplianceSummaryByConfigRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getComplianceSummaryByConfigRuleAsync(array $args = [])
 * @method \WP2Aws\Result getComplianceSummaryByResourceType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getComplianceSummaryByResourceTypeAsync(array $args = [])
 * @method \WP2Aws\Result getResourceConfigHistory(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getResourceConfigHistoryAsync(array $args = [])
 * @method \WP2Aws\Result listDiscoveredResources(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listDiscoveredResourcesAsync(array $args = [])
 * @method \WP2Aws\Result putConfigRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putConfigRuleAsync(array $args = [])
 * @method \WP2Aws\Result putConfigurationRecorder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putConfigurationRecorderAsync(array $args = [])
 * @method \WP2Aws\Result putDeliveryChannel(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putDeliveryChannelAsync(array $args = [])
 * @method \WP2Aws\Result putEvaluations(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putEvaluationsAsync(array $args = [])
 * @method \WP2Aws\Result startConfigRulesEvaluation(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startConfigRulesEvaluationAsync(array $args = [])
 * @method \WP2Aws\Result startConfigurationRecorder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startConfigurationRecorderAsync(array $args = [])
 * @method \WP2Aws\Result stopConfigurationRecorder(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise stopConfigurationRecorderAsync(array $args = [])
 */
class ConfigServiceClient extends WP2AwsClient {}
