<?php
namespace WP2Aws\CodeDeploy;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with AWS CodeDeploy
 *
 * @method \WP2Aws\Result addTagsToOnPremisesInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addTagsToOnPremisesInstancesAsync(array $args = [])
 * @method \WP2Aws\Result batchGetApplicationRevisions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise batchGetApplicationRevisionsAsync(array $args = [])
 * @method \WP2Aws\Result batchGetApplications(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise batchGetApplicationsAsync(array $args = [])
 * @method \WP2Aws\Result batchGetDeploymentGroups(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise batchGetDeploymentGroupsAsync(array $args = [])
 * @method \WP2Aws\Result batchGetDeploymentInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise batchGetDeploymentInstancesAsync(array $args = [])
 * @method \WP2Aws\Result batchGetDeployments(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise batchGetDeploymentsAsync(array $args = [])
 * @method \WP2Aws\Result batchGetOnPremisesInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise batchGetOnPremisesInstancesAsync(array $args = [])
 * @method \WP2Aws\Result continueDeployment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise continueDeploymentAsync(array $args = [])
 * @method \WP2Aws\Result createApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createApplicationAsync(array $args = [])
 * @method \WP2Aws\Result createDeployment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createDeploymentAsync(array $args = [])
 * @method \WP2Aws\Result createDeploymentConfig(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createDeploymentConfigAsync(array $args = [])
 * @method \WP2Aws\Result createDeploymentGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createDeploymentGroupAsync(array $args = [])
 * @method \WP2Aws\Result deleteApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteApplicationAsync(array $args = [])
 * @method \WP2Aws\Result deleteDeploymentConfig(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteDeploymentConfigAsync(array $args = [])
 * @method \WP2Aws\Result deleteDeploymentGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteDeploymentGroupAsync(array $args = [])
 * @method \WP2Aws\Result deregisterOnPremisesInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deregisterOnPremisesInstanceAsync(array $args = [])
 * @method \WP2Aws\Result getApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getApplicationAsync(array $args = [])
 * @method \WP2Aws\Result getApplicationRevision(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getApplicationRevisionAsync(array $args = [])
 * @method \WP2Aws\Result getDeployment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getDeploymentAsync(array $args = [])
 * @method \WP2Aws\Result getDeploymentConfig(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getDeploymentConfigAsync(array $args = [])
 * @method \WP2Aws\Result getDeploymentGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getDeploymentGroupAsync(array $args = [])
 * @method \WP2Aws\Result getDeploymentInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getDeploymentInstanceAsync(array $args = [])
 * @method \WP2Aws\Result getOnPremisesInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getOnPremisesInstanceAsync(array $args = [])
 * @method \WP2Aws\Result listApplicationRevisions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listApplicationRevisionsAsync(array $args = [])
 * @method \WP2Aws\Result listApplications(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listApplicationsAsync(array $args = [])
 * @method \WP2Aws\Result listDeploymentConfigs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listDeploymentConfigsAsync(array $args = [])
 * @method \WP2Aws\Result listDeploymentGroups(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listDeploymentGroupsAsync(array $args = [])
 * @method \WP2Aws\Result listDeploymentInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listDeploymentInstancesAsync(array $args = [])
 * @method \WP2Aws\Result listDeployments(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listDeploymentsAsync(array $args = [])
 * @method \WP2Aws\Result listGitHubAccountTokenNames(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listGitHubAccountTokenNamesAsync(array $args = [])
 * @method \WP2Aws\Result listOnPremisesInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listOnPremisesInstancesAsync(array $args = [])
 * @method \WP2Aws\Result registerApplicationRevision(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerApplicationRevisionAsync(array $args = [])
 * @method \WP2Aws\Result registerOnPremisesInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerOnPremisesInstanceAsync(array $args = [])
 * @method \WP2Aws\Result removeTagsFromOnPremisesInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeTagsFromOnPremisesInstancesAsync(array $args = [])
 * @method \WP2Aws\Result skipWaitTimeForInstanceTermination(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise skipWaitTimeForInstanceTerminationAsync(array $args = [])
 * @method \WP2Aws\Result stopDeployment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise stopDeploymentAsync(array $args = [])
 * @method \WP2Aws\Result updateApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApplicationAsync(array $args = [])
 * @method \WP2Aws\Result updateDeploymentGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateDeploymentGroupAsync(array $args = [])
 */
class CodeDeployClient extends WP2AwsClient {}
