<?php
namespace WP2Aws\DirectConnect;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **AWS Direct Connect** service.
 *
 * @method \WP2Aws\Result allocateConnectionOnInterconnect(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise allocateConnectionOnInterconnectAsync(array $args = [])
 * @method \WP2Aws\Result allocateHostedConnection(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise allocateHostedConnectionAsync(array $args = [])
 * @method \WP2Aws\Result allocatePrivateVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise allocatePrivateVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result allocatePublicVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise allocatePublicVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result associateConnectionWithLag(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise associateConnectionWithLagAsync(array $args = [])
 * @method \WP2Aws\Result associateHostedConnection(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise associateHostedConnectionAsync(array $args = [])
 * @method \WP2Aws\Result associateVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise associateVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result confirmConnection(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise confirmConnectionAsync(array $args = [])
 * @method \WP2Aws\Result confirmPrivateVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise confirmPrivateVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result confirmPublicVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise confirmPublicVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result createBGPPeer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createBGPPeerAsync(array $args = [])
 * @method \WP2Aws\Result createConnection(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createConnectionAsync(array $args = [])
 * @method \WP2Aws\Result createInterconnect(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createInterconnectAsync(array $args = [])
 * @method \WP2Aws\Result createLag(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createLagAsync(array $args = [])
 * @method \WP2Aws\Result createPrivateVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPrivateVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result createPublicVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPublicVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result deleteBGPPeer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteBGPPeerAsync(array $args = [])
 * @method \WP2Aws\Result deleteConnection(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteConnectionAsync(array $args = [])
 * @method \WP2Aws\Result deleteInterconnect(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteInterconnectAsync(array $args = [])
 * @method \WP2Aws\Result deleteLag(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteLagAsync(array $args = [])
 * @method \WP2Aws\Result deleteVirtualInterface(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteVirtualInterfaceAsync(array $args = [])
 * @method \WP2Aws\Result describeConnectionLoa(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConnectionLoaAsync(array $args = [])
 * @method \WP2Aws\Result describeConnections(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConnectionsAsync(array $args = [])
 * @method \WP2Aws\Result describeConnectionsOnInterconnect(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConnectionsOnInterconnectAsync(array $args = [])
 * @method \WP2Aws\Result describeHostedConnections(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeHostedConnectionsAsync(array $args = [])
 * @method \WP2Aws\Result describeInterconnectLoa(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeInterconnectLoaAsync(array $args = [])
 * @method \WP2Aws\Result describeInterconnects(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeInterconnectsAsync(array $args = [])
 * @method \WP2Aws\Result describeLags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLagsAsync(array $args = [])
 * @method \WP2Aws\Result describeLoa(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoaAsync(array $args = [])
 * @method \WP2Aws\Result describeLocations(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLocationsAsync(array $args = [])
 * @method \WP2Aws\Result describeTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \WP2Aws\Result describeVirtualGateways(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeVirtualGatewaysAsync(array $args = [])
 * @method \WP2Aws\Result describeVirtualInterfaces(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeVirtualInterfacesAsync(array $args = [])
 * @method \WP2Aws\Result disassociateConnectionFromLag(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disassociateConnectionFromLagAsync(array $args = [])
 * @method \WP2Aws\Result tagResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \WP2Aws\Result untagResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \WP2Aws\Result updateLag(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateLagAsync(array $args = [])
 */
class DirectConnectClient extends WP2AwsClient {}
