<?php
namespace WP2Aws\Swf;

use WP2Aws\WP2AwsClient;

/**
 * Amazon Simple Workflow Service (Amazon SWF) client.
 *
 * @method \WP2Aws\Result countClosedWorkflowExecutions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise countClosedWorkflowExecutionsAsync(array $args = [])
 * @method \WP2Aws\Result countOpenWorkflowExecutions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise countOpenWorkflowExecutionsAsync(array $args = [])
 * @method \WP2Aws\Result countPendingActivityTasks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise countPendingActivityTasksAsync(array $args = [])
 * @method \WP2Aws\Result countPendingDecisionTasks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise countPendingDecisionTasksAsync(array $args = [])
 * @method \WP2Aws\Result deprecateActivityType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deprecateActivityTypeAsync(array $args = [])
 * @method \WP2Aws\Result deprecateDomain(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deprecateDomainAsync(array $args = [])
 * @method \WP2Aws\Result deprecateWorkflowType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deprecateWorkflowTypeAsync(array $args = [])
 * @method \WP2Aws\Result describeActivityType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeActivityTypeAsync(array $args = [])
 * @method \WP2Aws\Result describeDomain(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeDomainAsync(array $args = [])
 * @method \WP2Aws\Result describeWorkflowExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeWorkflowExecutionAsync(array $args = [])
 * @method \WP2Aws\Result describeWorkflowType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeWorkflowTypeAsync(array $args = [])
 * @method \WP2Aws\Result getWorkflowExecutionHistory(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getWorkflowExecutionHistoryAsync(array $args = [])
 * @method \WP2Aws\Result listActivityTypes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listActivityTypesAsync(array $args = [])
 * @method \WP2Aws\Result listClosedWorkflowExecutions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listClosedWorkflowExecutionsAsync(array $args = [])
 * @method \WP2Aws\Result listDomains(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listDomainsAsync(array $args = [])
 * @method \WP2Aws\Result listOpenWorkflowExecutions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listOpenWorkflowExecutionsAsync(array $args = [])
 * @method \WP2Aws\Result listWorkflowTypes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listWorkflowTypesAsync(array $args = [])
 * @method \WP2Aws\Result pollForActivityTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise pollForActivityTaskAsync(array $args = [])
 * @method \WP2Aws\Result pollForDecisionTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise pollForDecisionTaskAsync(array $args = [])
 * @method \WP2Aws\Result recordActivityTaskHeartbeat(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise recordActivityTaskHeartbeatAsync(array $args = [])
 * @method \WP2Aws\Result registerActivityType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerActivityTypeAsync(array $args = [])
 * @method \WP2Aws\Result registerDomain(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerDomainAsync(array $args = [])
 * @method \WP2Aws\Result registerWorkflowType(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerWorkflowTypeAsync(array $args = [])
 * @method \WP2Aws\Result requestCancelWorkflowExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise requestCancelWorkflowExecutionAsync(array $args = [])
 * @method \WP2Aws\Result respondActivityTaskCanceled(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise respondActivityTaskCanceledAsync(array $args = [])
 * @method \WP2Aws\Result respondActivityTaskCompleted(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise respondActivityTaskCompletedAsync(array $args = [])
 * @method \WP2Aws\Result respondActivityTaskFailed(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise respondActivityTaskFailedAsync(array $args = [])
 * @method \WP2Aws\Result respondDecisionTaskCompleted(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise respondDecisionTaskCompletedAsync(array $args = [])
 * @method \WP2Aws\Result signalWorkflowExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise signalWorkflowExecutionAsync(array $args = [])
 * @method \WP2Aws\Result startWorkflowExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startWorkflowExecutionAsync(array $args = [])
 * @method \WP2Aws\Result terminateWorkflowExecution(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise terminateWorkflowExecutionAsync(array $args = [])
 */
class SwfClient extends WP2AwsClient {}
