<?php
namespace WP2Aws\CloudFormation;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **AWS CloudFormation** service.
 *
 * @method \WP2Aws\Result cancelUpdateStack(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise cancelUpdateStackAsync(array $args = [])
 * @method \WP2Aws\Result continueUpdateRollback(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise continueUpdateRollbackAsync(array $args = [])
 * @method \WP2Aws\Result createChangeSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createChangeSetAsync(array $args = [])
 * @method \WP2Aws\Result createStack(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createStackAsync(array $args = [])
 * @method \WP2Aws\Result deleteChangeSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteChangeSetAsync(array $args = [])
 * @method \WP2Aws\Result deleteStack(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteStackAsync(array $args = [])
 * @method \WP2Aws\Result describeAccountLimits(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAccountLimitsAsync(array $args = [])
 * @method \WP2Aws\Result describeChangeSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeChangeSetAsync(array $args = [])
 * @method \WP2Aws\Result describeStackEvents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeStackEventsAsync(array $args = [])
 * @method \WP2Aws\Result describeStackResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeStackResourceAsync(array $args = [])
 * @method \WP2Aws\Result describeStackResources(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeStackResourcesAsync(array $args = [])
 * @method \WP2Aws\Result describeStacks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeStacksAsync(array $args = [])
 * @method \WP2Aws\Result estimateTemplateCost(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise estimateTemplateCostAsync(array $args = [])
 * @method \WP2Aws\Result executeChangeSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise executeChangeSetAsync(array $args = [])
 * @method \WP2Aws\Result getStackPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getStackPolicyAsync(array $args = [])
 * @method \WP2Aws\Result getTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getTemplateAsync(array $args = [])
 * @method \WP2Aws\Result getTemplateSummary(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getTemplateSummaryAsync(array $args = [])
 * @method \WP2Aws\Result listChangeSets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listChangeSetsAsync(array $args = [])
 * @method \WP2Aws\Result listExports(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listExportsAsync(array $args = [])
 * @method \WP2Aws\Result listImports(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listImportsAsync(array $args = [])
 * @method \WP2Aws\Result listStackResources(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listStackResourcesAsync(array $args = [])
 * @method \WP2Aws\Result listStacks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listStacksAsync(array $args = [])
 * @method \WP2Aws\Result setStackPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setStackPolicyAsync(array $args = [])
 * @method \WP2Aws\Result signalResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise signalResourceAsync(array $args = [])
 * @method \WP2Aws\Result updateStack(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateStackAsync(array $args = [])
 * @method \WP2Aws\Result validateTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise validateTemplateAsync(array $args = [])
 */
class CloudFormationClient extends WP2AwsClient {}
