<?php
namespace WP2Aws\Waf;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **AWS WAF** service.
 *
 * @method \WP2Aws\Result createByteMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createByteMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result createIPSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createIPSetAsync(array $args = [])
 * @method \WP2Aws\Result createRateBasedRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createRateBasedRuleAsync(array $args = [])
 * @method \WP2Aws\Result createRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createRuleAsync(array $args = [])
 * @method \WP2Aws\Result createSizeConstraintSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createSizeConstraintSetAsync(array $args = [])
 * @method \WP2Aws\Result createSqlInjectionMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createSqlInjectionMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result createWebACL(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createWebACLAsync(array $args = [])
 * @method \WP2Aws\Result createXssMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createXssMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result deleteByteMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteByteMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result deleteIPSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteIPSetAsync(array $args = [])
 * @method \WP2Aws\Result deleteRateBasedRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteRateBasedRuleAsync(array $args = [])
 * @method \WP2Aws\Result deleteRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteRuleAsync(array $args = [])
 * @method \WP2Aws\Result deleteSizeConstraintSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteSizeConstraintSetAsync(array $args = [])
 * @method \WP2Aws\Result deleteSqlInjectionMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteSqlInjectionMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result deleteWebACL(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteWebACLAsync(array $args = [])
 * @method \WP2Aws\Result deleteXssMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteXssMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result getByteMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getByteMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result getChangeToken(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getChangeTokenAsync(array $args = [])
 * @method \WP2Aws\Result getChangeTokenStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getChangeTokenStatusAsync(array $args = [])
 * @method \WP2Aws\Result getIPSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getIPSetAsync(array $args = [])
 * @method \WP2Aws\Result getRateBasedRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getRateBasedRuleAsync(array $args = [])
 * @method \WP2Aws\Result getRateBasedRuleManagedKeys(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getRateBasedRuleManagedKeysAsync(array $args = [])
 * @method \WP2Aws\Result getRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getRuleAsync(array $args = [])
 * @method \WP2Aws\Result getSampledRequests(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSampledRequestsAsync(array $args = [])
 * @method \WP2Aws\Result getSizeConstraintSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSizeConstraintSetAsync(array $args = [])
 * @method \WP2Aws\Result getSqlInjectionMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getSqlInjectionMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result getWebACL(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getWebACLAsync(array $args = [])
 * @method \WP2Aws\Result getXssMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise getXssMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result listByteMatchSets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listByteMatchSetsAsync(array $args = [])
 * @method \WP2Aws\Result listIPSets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listIPSetsAsync(array $args = [])
 * @method \WP2Aws\Result listRateBasedRules(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listRateBasedRulesAsync(array $args = [])
 * @method \WP2Aws\Result listRules(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listRulesAsync(array $args = [])
 * @method \WP2Aws\Result listSizeConstraintSets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listSizeConstraintSetsAsync(array $args = [])
 * @method \WP2Aws\Result listSqlInjectionMatchSets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listSqlInjectionMatchSetsAsync(array $args = [])
 * @method \WP2Aws\Result listWebACLs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listWebACLsAsync(array $args = [])
 * @method \WP2Aws\Result listXssMatchSets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listXssMatchSetsAsync(array $args = [])
 * @method \WP2Aws\Result updateByteMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateByteMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result updateIPSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateIPSetAsync(array $args = [])
 * @method \WP2Aws\Result updateRateBasedRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateRateBasedRuleAsync(array $args = [])
 * @method \WP2Aws\Result updateRule(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateRuleAsync(array $args = [])
 * @method \WP2Aws\Result updateSizeConstraintSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateSizeConstraintSetAsync(array $args = [])
 * @method \WP2Aws\Result updateSqlInjectionMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateSqlInjectionMatchSetAsync(array $args = [])
 * @method \WP2Aws\Result updateWebACL(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateWebACLAsync(array $args = [])
 * @method \WP2Aws\Result updateXssMatchSet(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateXssMatchSetAsync(array $args = [])
 */
class WafClient extends WP2AwsClient {}
