<?php
namespace WP2Aws\ElasticBeanstalk;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **AWS Elastic Beanstalk** service.
 *
 * @method \WP2Aws\Result abortEnvironmentUpdate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise abortEnvironmentUpdateAsync(array $args = [])
 * @method \WP2Aws\Result applyEnvironmentManagedAction(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise applyEnvironmentManagedActionAsync(array $args = [])
 * @method \WP2Aws\Result checkDNSAvailability(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise checkDNSAvailabilityAsync(array $args = [])
 * @method \WP2Aws\Result composeEnvironments(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise composeEnvironmentsAsync(array $args = [])
 * @method \WP2Aws\Result createApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createApplicationAsync(array $args = [])
 * @method \WP2Aws\Result createApplicationVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createApplicationVersionAsync(array $args = [])
 * @method \WP2Aws\Result createConfigurationTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createConfigurationTemplateAsync(array $args = [])
 * @method \WP2Aws\Result createEnvironment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createEnvironmentAsync(array $args = [])
 * @method \WP2Aws\Result createPlatformVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createPlatformVersionAsync(array $args = [])
 * @method \WP2Aws\Result createStorageLocation(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createStorageLocationAsync(array $args = [])
 * @method \WP2Aws\Result deleteApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteApplicationAsync(array $args = [])
 * @method \WP2Aws\Result deleteApplicationVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteApplicationVersionAsync(array $args = [])
 * @method \WP2Aws\Result deleteConfigurationTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteConfigurationTemplateAsync(array $args = [])
 * @method \WP2Aws\Result deleteEnvironmentConfiguration(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteEnvironmentConfigurationAsync(array $args = [])
 * @method \WP2Aws\Result deletePlatformVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deletePlatformVersionAsync(array $args = [])
 * @method \WP2Aws\Result describeApplicationVersions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeApplicationVersionsAsync(array $args = [])
 * @method \WP2Aws\Result describeApplications(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeApplicationsAsync(array $args = [])
 * @method \WP2Aws\Result describeConfigurationOptions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConfigurationOptionsAsync(array $args = [])
 * @method \WP2Aws\Result describeConfigurationSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConfigurationSettingsAsync(array $args = [])
 * @method \WP2Aws\Result describeEnvironmentHealth(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEnvironmentHealthAsync(array $args = [])
 * @method \WP2Aws\Result describeEnvironmentManagedActionHistory(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEnvironmentManagedActionHistoryAsync(array $args = [])
 * @method \WP2Aws\Result describeEnvironmentManagedActions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEnvironmentManagedActionsAsync(array $args = [])
 * @method \WP2Aws\Result describeEnvironmentResources(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEnvironmentResourcesAsync(array $args = [])
 * @method \WP2Aws\Result describeEnvironments(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEnvironmentsAsync(array $args = [])
 * @method \WP2Aws\Result describeEvents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEventsAsync(array $args = [])
 * @method \WP2Aws\Result describeInstancesHealth(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeInstancesHealthAsync(array $args = [])
 * @method \WP2Aws\Result describePlatformVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describePlatformVersionAsync(array $args = [])
 * @method \WP2Aws\Result listAvailableSolutionStacks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAvailableSolutionStacksAsync(array $args = [])
 * @method \WP2Aws\Result listPlatformVersions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listPlatformVersionsAsync(array $args = [])
 * @method \WP2Aws\Result rebuildEnvironment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise rebuildEnvironmentAsync(array $args = [])
 * @method \WP2Aws\Result requestEnvironmentInfo(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise requestEnvironmentInfoAsync(array $args = [])
 * @method \WP2Aws\Result restartAppServer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise restartAppServerAsync(array $args = [])
 * @method \WP2Aws\Result retrieveEnvironmentInfo(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise retrieveEnvironmentInfoAsync(array $args = [])
 * @method \WP2Aws\Result swapEnvironmentCNAMEs(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise swapEnvironmentCNAMEsAsync(array $args = [])
 * @method \WP2Aws\Result terminateEnvironment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise terminateEnvironmentAsync(array $args = [])
 * @method \WP2Aws\Result updateApplication(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApplicationAsync(array $args = [])
 * @method \WP2Aws\Result updateApplicationResourceLifecycle(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApplicationResourceLifecycleAsync(array $args = [])
 * @method \WP2Aws\Result updateApplicationVersion(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateApplicationVersionAsync(array $args = [])
 * @method \WP2Aws\Result updateConfigurationTemplate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateConfigurationTemplateAsync(array $args = [])
 * @method \WP2Aws\Result updateEnvironment(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateEnvironmentAsync(array $args = [])
 * @method \WP2Aws\Result validateConfigurationSettings(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise validateConfigurationSettingsAsync(array $args = [])
 */
class ElasticBeanstalkClient extends WP2AwsClient {}
