<?php
namespace WP2Aws\DatabaseMigrationService;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **AWS Database Migration Service** service.
 * @method \WP2Aws\Result addTagsToResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addTagsToResourceAsync(array $args = [])
 * @method \WP2Aws\Result createEndpoint(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createEndpointAsync(array $args = [])
 * @method \WP2Aws\Result createEventSubscription(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createEventSubscriptionAsync(array $args = [])
 * @method \WP2Aws\Result createReplicationInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createReplicationInstanceAsync(array $args = [])
 * @method \WP2Aws\Result createReplicationSubnetGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createReplicationSubnetGroupAsync(array $args = [])
 * @method \WP2Aws\Result createReplicationTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createReplicationTaskAsync(array $args = [])
 * @method \WP2Aws\Result deleteCertificate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteCertificateAsync(array $args = [])
 * @method \WP2Aws\Result deleteEndpoint(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteEndpointAsync(array $args = [])
 * @method \WP2Aws\Result deleteEventSubscription(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteEventSubscriptionAsync(array $args = [])
 * @method \WP2Aws\Result deleteReplicationInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteReplicationInstanceAsync(array $args = [])
 * @method \WP2Aws\Result deleteReplicationSubnetGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteReplicationSubnetGroupAsync(array $args = [])
 * @method \WP2Aws\Result deleteReplicationTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteReplicationTaskAsync(array $args = [])
 * @method \WP2Aws\Result describeAccountAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAccountAttributesAsync(array $args = [])
 * @method \WP2Aws\Result describeCertificates(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeCertificatesAsync(array $args = [])
 * @method \WP2Aws\Result describeConnections(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeConnectionsAsync(array $args = [])
 * @method \WP2Aws\Result describeEndpointTypes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEndpointTypesAsync(array $args = [])
 * @method \WP2Aws\Result describeEndpoints(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEndpointsAsync(array $args = [])
 * @method \WP2Aws\Result describeEventCategories(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEventCategoriesAsync(array $args = [])
 * @method \WP2Aws\Result describeEventSubscriptions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEventSubscriptionsAsync(array $args = [])
 * @method \WP2Aws\Result describeEvents(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeEventsAsync(array $args = [])
 * @method \WP2Aws\Result describeOrderableReplicationInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeOrderableReplicationInstancesAsync(array $args = [])
 * @method \WP2Aws\Result describeRefreshSchemasStatus(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeRefreshSchemasStatusAsync(array $args = [])
 * @method \WP2Aws\Result describeReplicationInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeReplicationInstancesAsync(array $args = [])
 * @method \WP2Aws\Result describeReplicationSubnetGroups(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeReplicationSubnetGroupsAsync(array $args = [])
 * @method \WP2Aws\Result describeReplicationTasks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeReplicationTasksAsync(array $args = [])
 * @method \WP2Aws\Result describeSchemas(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeSchemasAsync(array $args = [])
 * @method \WP2Aws\Result describeTableStatistics(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTableStatisticsAsync(array $args = [])
 * @method \WP2Aws\Result importCertificate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise importCertificateAsync(array $args = [])
 * @method \WP2Aws\Result listTagsForResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \WP2Aws\Result modifyEndpoint(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyEndpointAsync(array $args = [])
 * @method \WP2Aws\Result modifyEventSubscription(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyEventSubscriptionAsync(array $args = [])
 * @method \WP2Aws\Result modifyReplicationInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyReplicationInstanceAsync(array $args = [])
 * @method \WP2Aws\Result modifyReplicationSubnetGroup(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyReplicationSubnetGroupAsync(array $args = [])
 * @method \WP2Aws\Result modifyReplicationTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyReplicationTaskAsync(array $args = [])
 * @method \WP2Aws\Result refreshSchemas(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise refreshSchemasAsync(array $args = [])
 * @method \WP2Aws\Result reloadTables(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise reloadTablesAsync(array $args = [])
 * @method \WP2Aws\Result removeTagsFromResource(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeTagsFromResourceAsync(array $args = [])
 * @method \WP2Aws\Result startReplicationTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startReplicationTaskAsync(array $args = [])
 * @method \WP2Aws\Result stopReplicationTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise stopReplicationTaskAsync(array $args = [])
 * @method \WP2Aws\Result testConnection(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise testConnectionAsync(array $args = [])
 */
class DatabaseMigrationServiceClient extends WP2AwsClient {}
