<?php
namespace WP2Aws\ElasticLoadBalancing;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with the **Elastic Load Balancing** service.
 *
 * @method \WP2Aws\Result addTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise addTagsAsync(array $args = [])
 * @method \WP2Aws\Result applySecurityGroupsToLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise applySecurityGroupsToLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result attachLoadBalancerToSubnets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise attachLoadBalancerToSubnetsAsync(array $args = [])
 * @method \WP2Aws\Result configureHealthCheck(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise configureHealthCheckAsync(array $args = [])
 * @method \WP2Aws\Result createAppCookieStickinessPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createAppCookieStickinessPolicyAsync(array $args = [])
 * @method \WP2Aws\Result createLBCookieStickinessPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createLBCookieStickinessPolicyAsync(array $args = [])
 * @method \WP2Aws\Result createLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result createLoadBalancerListeners(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createLoadBalancerListenersAsync(array $args = [])
 * @method \WP2Aws\Result createLoadBalancerPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createLoadBalancerPolicyAsync(array $args = [])
 * @method \WP2Aws\Result deleteLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result deleteLoadBalancerListeners(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteLoadBalancerListenersAsync(array $args = [])
 * @method \WP2Aws\Result deleteLoadBalancerPolicy(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteLoadBalancerPolicyAsync(array $args = [])
 * @method \WP2Aws\Result deregisterInstancesFromLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deregisterInstancesFromLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result describeAccountLimits(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeAccountLimitsAsync(array $args = [])
 * @method \WP2Aws\Result describeInstanceHealth(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeInstanceHealthAsync(array $args = [])
 * @method \WP2Aws\Result describeLoadBalancerAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoadBalancerAttributesAsync(array $args = [])
 * @method \WP2Aws\Result describeLoadBalancerPolicies(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoadBalancerPoliciesAsync(array $args = [])
 * @method \WP2Aws\Result describeLoadBalancerPolicyTypes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoadBalancerPolicyTypesAsync(array $args = [])
 * @method \WP2Aws\Result describeLoadBalancers(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeLoadBalancersAsync(array $args = [])
 * @method \WP2Aws\Result describeTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTagsAsync(array $args = [])
 * @method \WP2Aws\Result detachLoadBalancerFromSubnets(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise detachLoadBalancerFromSubnetsAsync(array $args = [])
 * @method \WP2Aws\Result disableAvailabilityZonesForLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise disableAvailabilityZonesForLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result enableAvailabilityZonesForLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise enableAvailabilityZonesForLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result modifyLoadBalancerAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise modifyLoadBalancerAttributesAsync(array $args = [])
 * @method \WP2Aws\Result registerInstancesWithLoadBalancer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerInstancesWithLoadBalancerAsync(array $args = [])
 * @method \WP2Aws\Result removeTags(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise removeTagsAsync(array $args = [])
 * @method \WP2Aws\Result setLoadBalancerListenerSSLCertificate(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setLoadBalancerListenerSSLCertificateAsync(array $args = [])
 * @method \WP2Aws\Result setLoadBalancerPoliciesForBackendServer(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setLoadBalancerPoliciesForBackendServerAsync(array $args = [])
 * @method \WP2Aws\Result setLoadBalancerPoliciesOfListener(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise setLoadBalancerPoliciesOfListenerAsync(array $args = [])
 */
class ElasticLoadBalancingClient extends WP2AwsClient {}
