<?php
namespace WP2Aws\Ecs;

use WP2Aws\WP2AwsClient;

/**
 * This client is used to interact with **Amazon ECS**.
 *
 * @method \WP2Aws\Result createCluster(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createClusterAsync(array $args = [])
 * @method \WP2Aws\Result createService(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise createServiceAsync(array $args = [])
 * @method \WP2Aws\Result deleteAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteAttributesAsync(array $args = [])
 * @method \WP2Aws\Result deleteCluster(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteClusterAsync(array $args = [])
 * @method \WP2Aws\Result deleteService(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deleteServiceAsync(array $args = [])
 * @method \WP2Aws\Result deregisterContainerInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deregisterContainerInstanceAsync(array $args = [])
 * @method \WP2Aws\Result deregisterTaskDefinition(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise deregisterTaskDefinitionAsync(array $args = [])
 * @method \WP2Aws\Result describeClusters(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeClustersAsync(array $args = [])
 * @method \WP2Aws\Result describeContainerInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeContainerInstancesAsync(array $args = [])
 * @method \WP2Aws\Result describeServices(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeServicesAsync(array $args = [])
 * @method \WP2Aws\Result describeTaskDefinition(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTaskDefinitionAsync(array $args = [])
 * @method \WP2Aws\Result describeTasks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise describeTasksAsync(array $args = [])
 * @method \WP2Aws\Result discoverPollEndpoint(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise discoverPollEndpointAsync(array $args = [])
 * @method \WP2Aws\Result listAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listAttributesAsync(array $args = [])
 * @method \WP2Aws\Result listClusters(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listClustersAsync(array $args = [])
 * @method \WP2Aws\Result listContainerInstances(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listContainerInstancesAsync(array $args = [])
 * @method \WP2Aws\Result listServices(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listServicesAsync(array $args = [])
 * @method \WP2Aws\Result listTaskDefinitionFamilies(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTaskDefinitionFamiliesAsync(array $args = [])
 * @method \WP2Aws\Result listTaskDefinitions(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTaskDefinitionsAsync(array $args = [])
 * @method \WP2Aws\Result listTasks(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise listTasksAsync(array $args = [])
 * @method \WP2Aws\Result putAttributes(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise putAttributesAsync(array $args = [])
 * @method \WP2Aws\Result registerContainerInstance(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerContainerInstanceAsync(array $args = [])
 * @method \WP2Aws\Result registerTaskDefinition(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise registerTaskDefinitionAsync(array $args = [])
 * @method \WP2Aws\Result runTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise runTaskAsync(array $args = [])
 * @method \WP2Aws\Result startTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise startTaskAsync(array $args = [])
 * @method \WP2Aws\Result stopTask(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise stopTaskAsync(array $args = [])
 * @method \WP2Aws\Result submitContainerStateChange(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise submitContainerStateChangeAsync(array $args = [])
 * @method \WP2Aws\Result submitTaskStateChange(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise submitTaskStateChangeAsync(array $args = [])
 * @method \WP2Aws\Result updateContainerAgent(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateContainerAgentAsync(array $args = [])
 * @method \WP2Aws\Result updateContainerInstancesState(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateContainerInstancesStateAsync(array $args = [])
 * @method \WP2Aws\Result updateService(array $args = [])
 * @method \WP2GuzzleHttp\Promise\Promise updateServiceAsync(array $args = [])
 */
class EcsClient extends WP2AwsClient {}
